declare module 'feather-icons-react'
declare module 'google-maps-react';
declare module 'swiper';
declare module 'react-joyride';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
declare module '*.webp';
declare module '*.svg';